# Generated by Django 4.0 on 2021-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('about_me', models.TextField(verbose_name='about me')),
                ('age', models.IntegerField(verbose_name='age')),
                ('current_job', models.CharField(max_length=150, verbose_name='current job ')),
                ('profile_pic', models.ImageField(upload_to='media', verbose_name='profile pic')),
                ('about_pic', models.ImageField(upload_to='media', verbose_name='about pic')),
                ('local', models.CharField(max_length=254, verbose_name='localisation')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('facebook', models.SlugField(verbose_name='facebook')),
                ('instgram', models.SlugField(verbose_name='instgram')),
                ('twitter', models.SlugField(verbose_name='twitter')),
                ('linkedin', models.SlugField(verbose_name='linkedin')),
                ('gmail', models.CharField(max_length=150, verbose_name='gmail')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Graduation_year', models.IntegerField(verbose_name='graduation year')),
                ('university_school', models.CharField(max_length=254, verbose_name='university or school name')),
                ('speciality', models.CharField(max_length=254, verbose_name='speciality')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='project name')),
                ('description', models.TextField(verbose_name='description')),
                ('_image', models.ImageField(upload_to='meia', verbose_name='project image')),
                ('github', models.SlugField(verbose_name='github link')),
                ('slug', models.SlugField(verbose_name='project link')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=254, verbose_name='company name')),
                ('yearOfWorking', models.IntegerField(verbose_name='year of working ')),
                ('_start', models.DateField(verbose_name='day of start')),
                ('_end', models.DateField(verbose_name='date of end')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
    ]
